const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvis', {
  onState: (cb) => ipcRenderer.on('state', (_e, list) => cb(list)),
  onShown: (cb) => ipcRenderer.on('panel-shown', () => cb()),
  onOpenSession: (cb) => ipcRenderer.on('open-session', (_e, id) => cb(id)),
  getState: () => ipcRenderer.invoke('state:get'),
  clearFinished: () => ipcRenderer.invoke('state:clear'),
  hidePanel: () => ipcRenderer.invoke('panel:hide'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  openChat: (sessionId) => ipcRenderer.invoke('chat:open', sessionId),
  closeChat: () => ipcRenderer.invoke('chat:close'),
  onChatAppend: (cb) => ipcRenderer.on('chat:append', (_e, data) => cb(data)),
  focusTerminal: (sessionId) => ipcRenderer.invoke('terminal:focus', sessionId),
  sendReply: (sessionId, text) => ipcRenderer.invoke('session:reply', sessionId, text),
  pingTerminal: (sessionId) => ipcRenderer.invoke('terminal:ping', sessionId),
  answerQuestion: (sessionId, choice) => ipcRenderer.invoke('question:answer', sessionId, choice),
  getCommands: (sessionId) => ipcRenderer.invoke('commands:get', sessionId),
  setModel: (sessionId, model) => ipcRenderer.invoke('session:setModel', sessionId, model),
  setEffort: (sessionId, level) => ipcRenderer.invoke('session:setEffort', sessionId, level),
  setPin: (sessionId, pinned) => ipcRenderer.invoke('session:setPin', sessionId, pinned),
  getMeta: () => ipcRenderer.invoke('app:meta'),
  onPlugins: (cb) => ipcRenderer.on('plugins', (_e, list) => cb(list)),
  getPlugins: () => ipcRenderer.invoke('plugins:status'),
  pluginCmd: (id, cmd, args) => ipcRenderer.invoke('plugins:cmd', id, cmd, args),
  getUsage: (period) => ipcRenderer.invoke('usage:summary', period),
  getLimit: () => ipcRenderer.invoke('limit:get'),
  onLimitState: (cb) => ipcRenderer.on('limit-state', (_e, l) => cb(l)),
  getSessionUsage: (id) => ipcRenderer.invoke('usage:session', id),
  getHistory: () => ipcRenderer.invoke('history:get'),
});
